### ISSUE TITLE
`rake test` failing with Rails 3.2.9 and minitest-rails HEAD

### ISSUE THREAD

**Issue by mybuddymichael** [minitest/minitest-rails#87]
Getting this when running `rake test`:

```
# Running tests:

/Users/michael/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/activesupport-3.2.9/lib/active_support/testing/setup_and_teardown.rb:65:in `run': undefined local variable or method `name' for #<IcpTest:0x007fd6a48ab998> (NameError)
        from /Users/michael/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/minitest-4.3.2/lib/minitest/unit.rb:912:in `block in _run_suite'
        from /Users/michael/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/minitest-4.3.2/lib/minitest/unit.rb:905:in `map'
        from /Users/michael/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/minitest-4.3.2/lib/minitest/unit.rb:905:in `_run_suite'
        from /Users/michael/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/minitest-4.3.2/lib/minitest/unit.rb:892:in `block in _run_suites'
        from /Users/michael/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/minitest-4.3.2/lib/minitest/unit.rb:892:in `map'
        from /Users/michael/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/minitest-4.3.2/lib/minitest/unit.rb:892:in `_run_suites'
        from /Users/michael/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/minitest-4.3.2/lib/minitest/unit.rb:860:in `_run_anything'
        from /Users/michael/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/minitest-4.3.2/lib/minitest/unit.rb:1053:in `run_tests'
        from /Users/michael/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/minitest-4.3.2/lib/minitest/unit.rb:1040:in `block in _run'
        from /Users/michael/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/minitest-4.3.2/lib/minitest/unit.rb:1039:in `each'
        from /Users/michael/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/minitest-4.3.2/lib/minitest/unit.rb:1039:in `_run'
        from /Users/michael/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/minitest-4.3.2/lib/minitest/unit.rb:1028:in `run'
        from /Users/michael/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/minitest-4.3.2/lib/minitest/unit.rb:782:in `block in autorun'
Errors running test:units! #<RuntimeError: Command failed with status (1): [ruby -I"lib:test" -I"/Users/michael/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/rake-10.0.2/lib" "/Users/michael/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/rake-10.0.2/lib/rake/rake_test_loader.rb" "test/unit/**/*_test.rb" ]>
```

**Comment by azurewraith** [comment]
FWIW, I just had this happen to me, I was upgrading a Rails 3.2.x project to use Ruby 2.1.2 and it ended up being `test-unit` snuck into my Gemfile.lock via an outside gem (in this case `p4ruby` `2014.4`).

Once I forcibly removed `test-unit` from my `Gemfile.lock` the error went away.

**Comment by blowmage** [comment]
:+1:

**Comment by zenspider** [comment]
Perforce brethren!
